### PR TITLE
CashFusion

### PR DESCRIPTION
**Pull request by sneurlax**
See https://github.com/cypherstack/fusiondart/pull/4 and https://github.com/cypherstack/stack_wallet/issues/681 for more information about the work required to get to this point.

TODO:
 - [x] Test with Tor disabled in Stack Wallet
 - [x] Test with Tor enabled in Stack Wallet (`torForOvert: true`)

### CODE REVIEW

**Comment by sneurlax** [comment]
Closes #681

**Comment by sneurlax** [comment]
Thank you @julian-CStack for fixing the tests on this

**Comment by sneurlax** [comment]
... and for fixing many many many other things lol

**Review by julian-CStack — APPROVED** [review]
probably good

**Pull request merged**
