### PR TITLE
Add xlm

### PR DESCRIPTION
**Pull request by Likho**

### CODE REVIEW

**Comment by julian-CStack** [comment]
get price tests need to be modified to handle xlm

**Comment by Likho** [comment]
>

**Comment by Likho** [comment]
>

**Comment by Likho** [comment]
> [Jul 27, 2023](#event-9935554938)

Updated @julian-CStack

**Comment by Likho** [comment]
> [Jul 27, 2023](#event-9935554938)

Updated @julian-CStack

**Pull request merged**
