### PR TITLE
WIP: monero.dart support

### PR DESCRIPTION
**Pull request by MrCyjaneK**
This PR includes

- Initial monero.dart support
- wallet creation
- wallet restore
- receiving address
- transaction history (partial)
- polyseed support
- transaction creation (crash - but "the code is there")

Build instructions:
- "The usual" ./build_all.sh
- extra: libwallet2_api_c.so has to be in /usr/lib or in the app's lib folder (1st one is recommended).

```bash
# before executing make sure that 'gcc g++ gperf' are installed (e.g. apt install -y gcc g++ gperf)
pushd $(mktemp -d)
git clone --recursive --branch rewrite-wip https://git.mrcyjanek.net/mrcyjanek/monero_c
pushd monero
git submodule update --init --force
popd
./apply_patches.sh
./build_single.sh $(gcc -dumpmachine) -j$(nproc)
unxz ./release/$(gcc -dumpmachine)_libwallet2_api_c.so.xz
sudo mv ./release/$(gcc -dumpmachine)_libwallet2_api_c.so /usr/lib/libwallet2_api_c.so
popd
```

or just grab it from https://static.mrcyjanek.net/monero_c/v0.18.3.3-RC10

x86_64 linux
```
sudo wget https://static.mrcyjanek.net/monero_c/v0.18.3.3-RC12/monero/x86_64-linux-gnu_libwallet2_api_c.so.xz -O /usr/lib/monero_libwallet2_api_c.so.xz
sudo unxz -f /usr/lib/monero_libwallet2_api_c.so.xz
sudo wget https://static.mrcyjanek.net/monero_c/v0.18.3.3-RC12/wownero/x86_64-linux-gnu_libwallet2_api_c.so.xz -O /usr/lib/wownero_libwallet2_api_c.so.xz
sudo unxz -f /usr/lib/wownero_libwallet2_api_c.so.xz
```

Features roadmap:

- [x] "Getting it to work"
- [x] Creation
- [x] Restore (polyseed + legacy)
- [x] https://github.com/cypherstack/flutter_libsparkmobile/pull/28
- [ ] passphrase offset (UI)
- [x] Making tx sending and wallet opening async
- [x] Proper app lifecycle
- [x] Backwards compatibility
- [x] wownero support ~~blocked by: https://git.wownero.com/wownero/wownero/issues/483 - I can use older tag, the same used by wowlet, but getting upstream to fix the issue is required anyway.~~ I've patched my way around.
- [x] Adding build scripts to the build_all.sh script

### CODE REVIEW

**Comment by MrCyjaneK** [comment]
I've reinstalled my vm and switched from ubuntu 20.04 to kubuntu 20.04, and there was a crash in one of plugins, this `linux/flutter/ephemeral/.plugin_symlinks/devicelocale/linux` file

<details>

<summary>Patch with backtrace</summary>

```patch
From e0510a18c61f9fabf27ac290d693fe62784f3814 Mon Sep 17 00:00:00 2001
From: Czarek Nakamoto <cyjan@mrcyjanek.net>
Date: Sat, 30 Mar 2024 08:29:43 +0100
Subject: [PATCH] FIX: double free or corruption in devicelocale_plugin.cc

(gdb) bt
0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
1  0x00007ffff4357859 in __GI_abort () at abort.c:79
2  0x00007ffff43c226e in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff44ec298 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
3  0x00007ffff43ca2fc in malloc_printerr (str=str@entry=0x7ffff44ee690 "double free or corruption (!prev)") at malloc.c:5347
4  0x00007ffff43cbfac in _int_free (av=0x7ffff4521b80 <main_arena>, p=0x2012e20, have_lock=<optimized out>) at malloc.c:4317
5  0x00007ffff7f0fd37 in get_category_locale(int) (category=6)
    at /home/user/stack_wallet/linux/flutter/ephemeral/.plugin_symlinks/devicelocale/linux/devicelocale_plugin.cc:52
{...}

After simply commenting out the line there were no more issues, and
stack_wallet continued to work as expected.

Issue occurs on kubuntu 20.04 (didn't occur on ubuntu 20.04).
---
 devicelocale_plugin.cc | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/devicelocale_plugin.cc b/devicelocale_plugin.cc
index c484d53..49fcf61 100644
--- a/devicelocale_plugin.cc
+++ b/devicelocale_plugin.cc
@@ -49,7 +49,7 @@ static gchar *get_category_locale(int category)
     bool no_locale = locale == nullptr
         || strncmp(locale, "LC_", sizeof("LC_") - 1) == 0;
     if (no_locale) {
-        g_free(locale);
+        // g_free(locale);
         return nullptr;
     } else {
         return locale;

```
</details>

**Comment by MrCyjaneK** [comment]
https://git.wownero.com/wownero/wownero/issues/484 the crash from above is resolved, monero_c code is also updated to reflect that change, and with this changes it works exactly the same on all (currently supported) platforms, that is
- Windows
- Linux
- MacOS
- Android
But that being said, the libraries are not packaged, I've workarounded xcode signing by symlinking the libraries and copying it to the right place as a xcode step, to make sure that they work use monero_c release v0.18.3.3-RC14 or newer, I'll most likely leave it as is, and just point to correct directory after adjusting build_all.sh script. (thanks @malik1004x for helping me out and pointing to a correct way to load a dylib on macos, if not for your help I'd most likely still be stuck learning how it works).

https://github.com/cypherstack/stack_wallet/pull/818/commits/27f7465ed6b929fdb3f2c7a2d92ce3abd5d9344e#diff-41c84f65620ae5e6d1f5708be89d2d7ca5b7f264127faccf746620036391e05c

I think that the code is ready for some initial review/testing/insight, things like syncing/creation/restore/sending should work across all platforms.

**Comment by MrCyjaneK** [comment]
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: HiveError: Cannot read, unknown typeId: 46. Did you forget to register an adapter?
```

**Comment by sneurlax** [comment]
Excuse me @MrCyjaneK, that was an accident and I can't reopen the PR myself.  Please reopen it if you can.  I pushed my own local copy of `cypherstack:monerodart` back, but you might want to push again (and feel free to force push--though you may not be allowed).

My apologies for the inconvenience.

**Comment by sneurlax** [comment]
Excuse me @MrCyjaneK, that was an accident. I pushed my own local copy of cypherstack:monerodart back, but you might want to push again (and feel free to force push--though you may not be allowed) and/or double-check commit shas etc.

*Takes another note to set up commit signing*

My apologies for any inconvenience.

**Comment by sneurlax** [comment]
Anyways, this is ready to merge to `cypherstack:monerodart`.  The more important merge is into `cypherstack:staging` (or `main`, if we want to eschew `staging` because of its current FROSTiness.

**Review by sneurlax — APPROVED** [review]
I approve these changes for merging into `cypherstack:monerodart` (not `staging` or `main`) as lightly reviewed and tested on:
 - Linux
 - macOS
 - iOS
 - Android
 - Windows
 I will need to more fully review the code before approving these changes for inclusion in staging/main.  I mostly just tested it and quickly looked over most code

**Pull request merged**
